[package]
name = "forest"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.7"
directories = "5"
anyhow = "1"

[dev-dependencies]
tempfile = "3"
