name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build test image (cached)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: builder
          tags: forest:builder
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run tests
        run: |
          docker run --rm forest:builder bash -c "git config --global user.name 'CI' && git config --global user.email 'ci@example.com' && cargo test --verbose"

